name: Ginkgo E2E Tests

on:
  schedule:
    - cron: '0 7 * * *'

  workflow_dispatch:

jobs:

  run-e2e-tests:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Disable Problem Matchers
        run: echo "::remove-matcher owner=actions-runner::"

      - name: Cache Go modules
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          enableCrossOsArchive: true

      - name: Enable Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/actions-problem-matcher.json"
            
      - name: Install dependencies
        run: go mod download

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Run Ginkgo E2E Tests and Generate Report
        run: go test -v -json ./tests | go-junit-report -set-exit-code > report.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Ginkgo E2E Test Results
          path: report.xml
          reporter: jest-junit